name: 使用ubuntu自带python打印hello world

on:
  workflow_dispatch:   # 手动触发

jobs:
  print-hello-world:
    name: 打印hello world
    runs-on: ubuntu-22.04

    steps:
      # 检出仓库代码
      - name: 检出仓库代码
        uses: actions/checkout@v4
        
      - name: 打印 Hello World
        run: |
          python3 hello.py
